In [1]:
import numpy as np

In [10]:
# Linear Regression

class LinearRegression:
    def __init__(self,learning_rate = 0.01, n_iter = 1000):
        self.bias  = None
        self.weights = None
        self.lr = learning_rate
        self.n_iter = n_iter

    def fit(self , x , y): # x_train , y_train
        m, n = x.shape # (number of samples , number of features)
        # step 1 - initialize params
        self.bias = 0
        self.weights = np.zeros(n)
        

        # Gradient descent
        for i in range(self.n_iter):
            
            # step 2 - calx - y_pred
            y_pred =  np.dot(x,self.weights)   +self.bias 

            # step 3 - calc gradient
            db = (1/m) * np.sum(y_pred - y)
            dw = (1/m) * np.dot(x.T , (y_pred - y))

            # step 4 - convergence theorem - params update
            self.bias -= self.lr*db
            self.weights -= self.lr*dw

    
    def predict(self,x):
        y_pred = self.bias +  np.dot(x,self.weights)
        return y_pred

In [11]:
x  = np.array([[1], [2],[3],[4], [5]])
y = np.array([2,4,6,8,10])

model = LinearRegression()
model.fit(x,y)

y_pred = model.predict(x)
print(y_pred)

[2.06850809 4.04226297 6.01601785 7.98977273 9.96352761]


In [25]:
#linear regression with ordinal least square

class LinearRegressionOLS:
    def __init__(self):
        self.bias = None
        self.weights = None

    def fit(self,x,y):
        m,n = x.shape

        x_b = np.c_[np.ones((m,1)),x]

        #normal equation
        theta = np.linalg.inv(x_b.T @ x_b) @ x_b.T @ y

        self.bias = theta[0]
        self.weights = theta[1:]

    def predict(self,x):
        y_pred =self.bias  + np.dot(x,self.weights)
        return y_pred

In [27]:
x  = np.array([[1], [2],[3],[4], [5]])
y = np.array([2,4,6,8,10])

model = LinearRegressionOLS()
model.fit(x,y)

y_pred = model.predict(x)
print(y_pred)
print(model.bias)
print(model.weights)

[ 2.  4.  6.  8. 10.]
5.662137425588298e-15
[2.]


In [28]:
import numpy as np

In [ ]:
class LogisticRegreRegression:
    def __init__(self,learning_rate = 0.1,n_iter = 1000):
        self.bias = None
        self.weights = None
        self.lr = learning_rate
        self.n_iter = n_iter

    def _sigmoid(self,z):
        return (1/(1+ np.exp(-z)))
    def fit(self,x,y):
        m,n = x.shape


        self.bias = 0
        self.weights = np.zeros(n)

        for i in range(self.n_iter):
            z = self.bias+ np.dot(x , self.weights)
            y_pred = self._sigmoid(z)


            db = (1/m) * (y_pred - y)
            dw = (1/m) * np.dot(x.T,(y_pred - y))

            self.bias -= self.lr * db
            self.weights -= self.lr * dw

    # finding probability
    def get_probabilities(self , x):
        z = self.bias+ np.dot(x , self.weights)
        probability = self._sigmoid(z)
        return probability
    
    # converting probabity in to classes
    def predict(self,x, threshold = 0.5):
        probabilities = self.get_probabilities(x)
        y_pred_bool = probabilities >= threshold
        return y_pred_bool.astype(int)


        

In [40]:
x = np.array([[1,2], [2,3],[3,4],[4,5]])
y = np.array([0,0,1,1])

model = LogisticRegreRegression()
model.fit(x,y)

y_pred = model.predict(x)
print(y_pred)

print(model.get_probabilities(x))

[0 0 1 1]
[0.03701722 0.04694058 0.972997   0.98153106]
