In [31]:
import numpy as np
arr = np.array([1,2,3,4])
print(type(arr))

<class 'numpy.ndarray'>


In [32]:
#Performance comparision
import time
# execting performance
size = 1_000_000

# python list

py_list = list(range(size))
start = time.time()

sq_list = [x**2 for x in py_list]
end = time.time()
print(f"python list time = {end- start} seconds")

#numpy arrays
np_arr = np.array(py_list)
start = time.time()
sq_array = np_arr ** 2
end = time.time()
print(f"numpy array time  = {end - start} , seconds")

python list time = 0.09902572631835938 seconds
numpy array time  = 0.002016782760620117 , seconds


In [33]:
# memory usage comparision
import sys

print("python list size:", sys.getsizeof(py_list)* len(py_list))
print("numpy array size= ",np_arr.nbytes)


python list size: 8000056000000
numpy array size=  8000000


In [34]:
# Numpy array creation

# list
arr  = np.array([1,2,3,4])
print(arr,type(arr))

arr2 = np.array([1,2,3,4,"prime",3.14]) # internally all converted to string
print(arr2,type(arr))

#2d arrays - matrix

arr3 = np.array([[1,2,3],[4,5,6]])
print(arr3,arr3.shape)


[1 2 3 4] <class 'numpy.ndarray'>
['1' '2' '3' '4' 'prime' '3.14'] <class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]] (2, 3)


In [35]:
# built in function
arr1 = np.zeros((3,3))
print(arr1,arr1.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] (3, 3)


In [36]:
arr2 = np.ones((3,3))
print(arr2,arr2.shape)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] (3, 3)


In [37]:
arr3 = np.full((2,3),5)
print(arr3.shape)

(2, 3)


In [38]:
arr4 = np.eye(3)
print(arr4,arr4.shape)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)


In [39]:
arr5 =  np.arange(1,20,2) # element in range (1,20)
print(arr5,arr5.shape)

[ 1  3  5  7  9 11 13 15 17 19] (10,)


In [40]:
arr6 = np.linspace(0,10,5)  # evenly spaced array
print(arr6,arr6.shape)


[ 0.   2.5  5.   7.5 10. ] (5,)


In [41]:
#   numpy array properties


arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)
print(arr.itemsize)

(3, 3)
9
2
int64
8


In [42]:
# change dtype

str_arr = np.array([1,2,3],dtype = "U")
print(str_arr,str_arr.dtype)

float_arr = np.array([1,2,3],dtype= 'float64')
print(str_arr,float_arr.dtype)

# creating new array with specific type from existing array

int_arr = float_arr.astype(np.int32)
print(int_arr,int_arr.dtype)

['1' '2' '3'] <U1
['1' '2' '3'] float64
[1 2 3] int32


In [43]:
#  operation on arrays
# reshapping
arr = np.array([1,2,3,4,5,6])
print(arr.shape)

reshaped  = arr.reshape((2,3)) # convert 1d to 2d
print(reshaped,reshaped.dtype)

flattened = arr.flatten() # convert 2d to 1d
print(flattened,flattened.shape)

(6,)
[[1 2 3]
 [4 5 6]] int64
[1 2 3 4 5 6] (6,)


In [44]:
# indexing

arr = np.array([1,2,3,4,5])
print(arr[0])

# indexing for 2d
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr[0][1]) 
print(arr[1][2])

1
2
6


In [45]:
# fancy indexing
# accesing element using integer array list insted using (:)

arr = np.array([1,2,3,4,5])
idx = [0,1,4]
print(arr[idx]) # print nums at given indices

# bollean masking (or indexing)
print(arr[arr>2])
print(arr[arr %2 == 0])

[1 2 5]
[3 4 5]
[2 4]


In [46]:
# slicing
arr = np.array([1,2,3,4,5,6,7])

print(arr[2:6])

[3 4 5 6]


In [47]:
# sliced list is a copy

py_list = [1,2,3,4,5]

cpy_list = py_list[1:4]
cpy_list[1] = 333

print(cpy_list)
print(py_list) # remain same

#sliced array is a view

np_arr  =np.array([1,2,3,4,5])

view_arr = np_arr[1:4] # [2,3,4]
view_arr[1] = 333

print(view_arr)
print(np_arr) # changes

# creating copy for array

copy_arr = np_arr[1:4].copy() #[2,3,4]
copy_arr[2] = 444
print(copy_arr)  
print(np_arr) #[1,2,3,4,5]  # remain same




[2, 333, 4]
[1, 2, 3, 4, 5]
[  2 333   4]
[  1   2 333   4   5]
[  2 333 444]
[  1   2 333   4   5]


In [49]:
# multidimensional array
#1d array
arr1d = np.array([1,2,3])
print(arr1d.ndim) #1


1


In [ ]:
# 2d array (matrix)

arr2d = np.array([[1,2,3],[4,5,6],
                  ])
print(arr2.ndim) # 2


2


In [51]:
# 3d array (tensor)

arr3d = np.array([[[1,2,3],
                  [4,5,6]],
                  [[7,8,9],
                   [10,11,12]]])

print(arr3d.ndim)

3


In [ ]:
# operation along axes


#2d
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
  
print(np.sum(arr2d)) # sum of entire array  - 45

sum_of_rows  = np.sum(arr2d,axis = 0)
print(sum_of_rows)  # [12 15 18]

sum_of_columns = np.sum(arr2d , axis = 1)
print(sum_of_rows) # [6 15 24]

# slicing
print(arr2d[0:3 , 1:3])


45
[12 15 18]
[12 15 18]
[[2 3]
 [5 6]
 [8 9]]


In [53]:
#3d
arr3d = np.array([[[1,2],[3,4],[5,6]] , [[7,8],[9,10],[11,12]]])

print(arr3d,arr3d.shape)

#indexing
print(arr3d[0][1][1])
print(arr3d[1][2][1])
print(arr3d[:,:,0])

print(arr3d[:,0,:])



[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
12
[[ 1  3  5]
 [ 7  9 11]]
[[1 2]
 [7 8]]


In [54]:
# data type

arr = np.array([1,2,3,4,5])
arr2 = np.array([1.0,2.0,3.0])
arr3  = np.array(["hello","world","prime","ai/ml"])

print(arr.dtype) #int 64
print(arr2.dtype) # float64
print(arr3.dtype) #u


# complex numbers

arr1 =  np.array([2+3j])
arr2 = np.array([5+8j])

print(arr1,arr1.dtype)
print(arr1+arr2)
print(arr2 - arr1)

# objects

arr = np.array(["hello",{1,2,3},{3.14}])
print(arr,arr.dtype)

int64
float64
<U5
[2.+3.j] complex128
[7.+11.j]
[3.+5.j]
['hello' {1, 2, 3} {3.14}] object


In [ ]:
# typecasting using astype

# changing the data type
new_arr = arr.astype("float64")
print(new_arr, new_arr.dtype)

new_arr = np.array([1,2,3,4,5],dtype = "float64")
print(new_arr , new_arr.dtype)



In [55]:
# vectorization

arr = np.array([1,2,3,4,5])

sq_arr = arr **2
print(sq_arr)

arr2 = np.array([6,7,8,9,10])
print(arr1 +arr2)

[ 1  4  9 16 25]
[ 8.+3.j  9.+3.j 10.+3.j 11.+3.j 12.+3.j]


In [56]:
# broadcasting

# broadcasting with a scalar
arr_mul10 = arr* 10 #  multiply by 10 to all nums
print(arr_mul10)

#Broadcasting with a vector
arr1d = np.array([1,2,3])
arr2d = np.array([[1,2,3],[4,5,6]])

print(arr1d + arr2d)


[10 20 30 40 50]
[[2 4 6]
 [5 7 9]]


In [57]:
 # standard vector normalization
arr = np.array([[1,2],[3,4]])

mean = np.mean(arr)
std_dev = np.std(arr)
normalized_arr = (arr - mean) /std_dev
print(normalized_arr)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


In [58]:
# column wise normaliztion
arr = np.array([[1,2],[3,4],[5,6]])
mean = np.mean(arr)

std_dev = np.std(arr)
normalized_arr = (arr - mean) / std_dev

print(normalized_arr)


[[-1.46385011 -0.87831007]
 [-0.29277002  0.29277002]
 [ 0.87831007  1.46385011]]


In [ ]:
# Useful mathmetical function

# Aggregation Function
arr = np.array([1,2,3,4,5])

print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.argmin(arr))
print(np.max(arr))
print(np.argmax(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

15
120
1
0
5
4
3.0
3.0
1.4142135623730951
2.0


In [65]:
#power function

arr = np.array([1,2,3,4,5])

print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,3))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [66]:

#Log and Exponential function

print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))



[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [67]:
#Rounding function

print(np.round(2.678))
print(np.floor(2.678))
print(np.ceil(2.678))
print(np.trunc(2.678))

3.0
2.0
3.0
2.0


In [68]:
# Miscellanous function

arr = np.array([1,2,-5,3,8,-4,2,5])

print(np.abs(arr))
print(np.sort(arr))
print(np.unique(arr))

[1 2 5 3 8 4 2 5]
[-5 -4  1  2  2  3  5  8]
[-5 -4  1  2  3  5  8]
